jetracer:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  front_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: front_wheel_joint
    pid: {p: 100, i: 10, d: 10}

  rear_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: rear_left_wheel_joint
    pid: {p: 100, i: 10, d: 10}
